### ISSUE TITLE
[Tool request] binaryninja-demo

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#1108]
http://binary.ninja/demo.html

**Comment by noptrix** [comment]
thx, will be added!

**Comment by noptrix** [comment]
added and released.

**Comment by psifertex** [comment]
Thanks for the interest in Binary Ninja, we're happy to have it included in BlackArch, but we do need to make sure people realize they must agree to the license (https://docs.binary.ninja/about/license/index.html#demo-license) before they use it. 

I notice in the current package file there's a link that says license:unknown -- not sure if it's possible to link to our license online or just put "evaluation/commercial" or something like that there. 

We can modify future versions of the demo to include that information in the startup dialog box as well which will solve it in a way better for everyone, but in the meantime, is it possible to also include a link to the license information somewhere in the install?

Also, it's worth noting here in case anyone is searching the issues here for Binary Ninja in the future that if anyone wants to install their personal or commercial license for binary ninja into BlackArch, it needs some tweaks that the demo doesn't. More info on that here: http://docs.binary.ninja/guide/troubleshooting/index.html#arch-linux

**Comment by noptrix** [comment]
@psifertex thanks for the info. we will fix the pkgbuild file and also make sure to link it to your license information.

**Comment by psifertex** [comment]
Much appreciated.

**Comment by noptrix** [comment]
@psifertex i think this should be fine now: https://github.com/BlackArch/blackarch/blob/18c56fa95f2f7699b7161881139e0b84e265783a/packages/binaryninja-demo/PKGBUILD - the LICENSE file is saved locally and gets installed in /usr/share/licenses/binaryninja-demo/LICENSE. The original LICENSE is pointed with your URL in the notes 'binaryninja-demo.install'. I also added a note about the personal/commercial usage.

Let me know if this is fine so I can close this issue here

**Comment by ChrisFernandez** [comment]
I do not know if is a good idea to add non-open licenses to blackarch... I personally will not use anything that has not an open source licence for many reasons, and security.
