### ISSUE TITLE
Eyewitness dependency issues

### ISSUE THREAD

**Issue by kurobeats** [BlackArch/blackarch#1137]
I'm not even sure if this is specifically a blackarch issue as the libraries are installed, but, here's what I'm getting after installing eyewitness on a remote box:

» sudo pacman -S eyewitness
resolving dependencies...
looking for conflicting packages...

Packages (3) ghost-py-0.2.3-1  python2-rdpy-1.3.2-1  eyewitness-542.8f85174-1

Total Download Size:   0.29 MiB
Total Installed Size:  2.19 MiB
...
» eyewitness 
[] RDP libraries not found.
[] Please run the script in the setup directory!

**Comment by hexcat** [comment]
Missing dependencies:

- python2-selenium
- python2-rsa (needed [here](https://github.com/ChrisTruncer/EyeWitness/blob/master/modules/rdp_module.py#L7))
- python2-pyvirtualdisplay
- easyprocess (NOT in repositories)

To resolve, install missing deps manually. Easyprocess dependency can be installed by:
`pip2 install --user easyprocess`

Removal command (when it will be added as package):
`pip2 uninstall easyprocess`

**Comment by noptrix** [comment]
will be fixed, thanks.

**Comment by hexcat** [comment]
python2-rsa probably should be a dependency for python2-rdpy

**Comment by hexcat** [comment]
Please note that python2-pyvirtualterminal requires at least one backend to be installed (Xvfb, Xephyr or Xvnc). I've tested eyewitness with "--web" option and it didn't work because of it.

setup.py solves this by [installing Xvfb](https://github.com/ChrisTruncer/EyeWitness/blob/62f1344e90fc26f74a58aa845e512268ab077466/setup/setup.sh#L37). A same approach would be adding xorg-server-xvfb as dependency to eyewitness, but this whould require users who want to use other backend to install it too.

**Comment by noptrix** [comment]
thx a lot. fixing it right now

**Comment by noptrix** [comment]
so fixed and released. thanks for your support.
