### ISSUE TITLE
[Tool request] OWASP Zaproxy

### ISSUE THREAD

**Issue by amuntner** [BlackArch/blackarch#1178]
Zaproxy the tool isn't in the repo, however the Zap python bindings library. 

https://www.owasp.org/index.php/OWASP_Zed_Attack_Proxy_Project

Zap is great and free, please include it

@psiinon is the project maintainer

**Comment by ChrisFernandez** [comment]
I though this was in the repo.. but if not.. yes.. I use it all the time, I stop using BURP long time a go because is closer source and zap is up to it or better at this point.

**Comment by psiinon** [comment]
Its mentioned on https://www.blackarch.org/tools.html but I think @amuntner is right, looks like only the ZAP python lib is includes.
ZAP just need Java 7+ (or docker).
Let me know if you need help with the packaging or any advice and guidance.
And good to hear that you've switched to ZAP :) Any feedback on things we could do better? We never get enough feedback :/

**Comment by ChrisFernandez** [comment]
@psiinon feedback... hmm well I have help a couple times in bumping packages.. but I really will like to be part of the project, why? because I work as a pentester, and I usually find tools I need the most faster than people learning, and sometimes blackarch is behind on that...  I use arch/blackarch now a days for all my business, and I recommend it to all my groups dc415,hispagatos, binaryfreedom etc etc  even thinking in doing some workshops here in San Francisco noisebridge. Been using linux since 1995, a hacker since I was born, and bla bla bla  https://keybase.io/cfernandez  I have coding skills that I will love to contribute to a good proyect, mostly one I actually use day by day..

**Comment by noptrix** [comment]
community/zaproxy 2.5.0-1 [installed]
    Integrated penetration testing tool for finding vulnerabilities in web applications

blackarch/zaproxy 2.5.0-1 (blackarch blackarch-webapp blackarch-fuzzer blackarch-proxy) [installed]
    Integrated penetration testing tool for finding vulnerabilities in web applications

we mirror the package in our repository via community. ArchLinux's community already includes it. What's the problem here?
