### ISSUE TITLE
Installation on the top of Arch Linux

### ISSUE THREAD

**Issue by Zhidomasson** [BlackArch/blackarch#1563]
Hello!
I tried to install Blackarch on the top of Arch linux for a really long time, nothing worked. Can you please write a good guide about this? There are a lot of questions in the internet about it, but I still haven't found the solution. Perphaps I'm not the only one.

P.S. Also a little notice: when installing from blackarch iso often system doesn't load after "reached graphical interface", but it can be fixed. 

New tools are cool, but there are already plenty of them, did you thing about a good article concerning installation with typical mistakes? It would be really helpful.
Thanks in advance.

**Comment by Miskalicious** [comment]
having a similar problem over here too. i can install a fair amount of the tools directly with pacman, but there are quite a few python-based tools that only throw errors when i try to run them. I've tried building from source with blackman as well - which only ends up posting a bunch of build errors.

I've also tried commenting out the core arch repos in /etc/pacman.conf (thinking it might be similar to kali's hardcore rule about ONLY using their repo) but i was mistaken there as well (so they're in the pacman.conf file again).

also (also) tried: straight running blackman blackarch, pacman -S blackarch, as well as installing a whole blackarch group via pacman (e.g. pacman -S blackarch-wireless). Since i've been having so many problems with python-based tools, i've also gone so far to install any python library/dependency i can find in /core /extra or /community just to see if there's something I'm missing - no dice. kinda frustrating to see errors when i've installed w3af and go to run it the first time.

there's some seriously dope tools in here, and I'll be damned if i have to go back to apt-get, but i'd rather have a small amount of working tools than a bunch error-prone python scripts. Seriously not trying to hate on the devs, this looks like a massive amount of work! just looking for some guidance, and regardless of these issues, big up to the devs for putting in all of this work!

**Comment by ikstream** [comment]
@Miskalicious could you please report broken packages here on github, so someone can have a look for it to fix it.

**Comment by narutowindy** [comment]
yes guys its not working on top of arch-linux..... please fix the issue... 

(if i know the things i wuld have helped you guys... may  be in the future......Noob........)

**Comment by NovaCygni** [comment]
Works perfectly fine not only on top of pure Archlinux but also flawlessly on Antargos, Manjaro and other Arch based distro's...
Never botherered with Blackman myself either as, the preferred format will be "sudo pacman -S blackarch --force"... you can then install ALL packages, with no problems at all (* so long as your using a up to date mirror, ie 
```
[blackarch]

SigLevel = Optional TrustAll
Server = http://blackarch.pi3rrot.net/blackarch/$repo/os/$arch
```

**Comment by saltasatelites** [comment]
SigLevel = Optional TrustAll   ???? That´s not recomended, and is dangerous too.
After run sh strap.sh you get all the master keys. So, there's no problem and is more secure use TrustedOnly

Usage --force isn't neither recommended nor necessary. A simple pacman -Syyu do the job better and without problems
This repos are always up to date:
[blackarch]
Server = https://www.blackarch.org/blackarch/$repo/os/$arch
Server = http://blackarch.tamcore.eu/$repo/os/$arch
Server = http://blackarch.pi3rrot.net/blackarch/$repo/os/$arch
Server = http://blackarch.leneveu.fr/blackarch/$repo/os/$arch
SigLevel = TrustedOnly

**Comment by NovaCygni** [comment]
@Miskalicious btw the command to update everything Python on your system and install/update all required dependencies is `sudo pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 sudo pip3 install -U`
@saltasatelites The SigLevel was merely a example of the Repo's being tested, that worked first time for the install, I would expect anyone who is using a Pentesting Distro to appreciate the importance of trusting any updates they do on a "Per package/Push" basis after the initial install...
As for the use of "--force", depending on which Archlinux setup you have installed, it is often required for the first time installation of the entire BlackArch toolsset, and is again not encouraged for general use outside of the "Solution" being provided at the time... Ie> Antargos and Manjaro will both require --force to be used.

P.S> Sup btw ;) Im the defacto BlackArch/Manjaro support person :)

**Comment by PedroSFreitas** [comment]
Following the nice replies from @saltasatelites and @NovaCygni and since the OP didn't reply for such long, I'm closing this issue.

If you, @Zhidomasson think it's a mistake, just reopen it please. Thanks.

**Comment by warloxian** [comment]
I've installed Black Arch full tool set inside of Arch Linux in a dell chromebook 11-3180. No problems. Also on a Macbook pro 5,5 inside of Manjero but it is missing a lot of tools. Also on an old Dell Studio with Arch, that's been my best set up so far as all tools installed with zero problems and all run fine so far. I am a 2 month newbie to Linux and I started south right away with Kali but went back to Mint as I needed some basic  training as I am a Windows man. I've deleted windows off all my machines and will only use windows as a virtual machine now. I am missing all Osint tools on my Manjero install though. I'm just rambling cause I want to hear the ridicule because I learn best when I'm being harassed
