### ISSUE TITLE
Black Arch Linux Tools on Kali Linux

### ISSUE THREAD

**Issue by FailGecko9800** [BlackArch/blackarch#1782]
Hi how are you...

i was wondering if there is a place that i can download all of the black arch linux tools so i can put them on my kali linux machine, because i find that black arch linux is a bit complicated and bit hard to use but it has so many awesome tools that i would love to have on my kali machine.

Do you think that you could point me in the right direction to get all the tools so i can import them into my kali machine

Thanks so much

**Comment by mrtnrdl** [comment]
You could always check out the tools repository and build it from source.

**Comment by FailGecko9800** [comment]
but how do i build it from source

you must be thinking i am pretty dumb for not knowing this
but i would not even know where to start and how to do any of this

do you have skype or some way i can contact you, because i need some help with this

kind regards
FailGecko

**Comment by ikstream** [comment]
There is usually a part in the readme on how to install or build the Tool you are looking for. 
If you have a look at a git repository you will see it.
Check https://github.com/arismelachroinos/lscript for example.
If you have any problems following the mentioned instructions in the readme you can ask politely at the repository of the individual projekt.

**Comment by mrtnrdl** [comment]
Or you could ask in the projects irc/gitter/slack channel for guidance.

**Comment by PedroSFreitas** [comment]
@FailGecko9800 
A few pointed you to some good information... I'm here just to add my humble opinion. :) feel free to ignore it.

I think you're probably missing the point of a Penetration Testing Linux Distribution. I see two options for using a Penetration Testing Distro: 1. you're a pentester (or need it to work on other fields that is quite similar) and 2. you are learning.
I believe you're in the second group (same as me to be honest ;) ). If so, as I said above, people pointed you to the right direction (building from source).

I'm closing this issue since it's pretty much out of the scope (it's not related to BlackArch itself). Although I'm not locking... If you think it's a mistake you can reopen and provide further info.

**Comment by darkarmymz** [comment]
Hello!

Since you want to use blackarch linux tools in a friendly and simple to use system (Kali Linux), you can dispense with kali linux and Install Arch Linux on your machine so you can install blackarch on top of arch linux.
the Tutorial:   https://www.youtube.com/watch?v=dKOHK7AIXsc

You can see this Tutorial

**Comment by FailGecko9800** [comment]
Hi.. how are you
I looked at the tutorial on YouTube and followed it... I actually can't install Pacman on my Kali machine because I don't know how... and the tutorial is a bit out of date... 
Can one of you contact me on: failgecko9800@gmail.com
And you can give me some instructions via email
Thank you
