### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by dr-cesar** [BlackArch/blackarch#1805]
mono-addins key is disabled on package integritty

**Comment by PedroSFreitas** [comment]
`mono-addins` is an Archlinux package, not maintained by BlackArch Team.

**I'm not 100% sure** of what you mean. Although I can suggest two things:
1. `sudo rm -rfv /var/cache/pacman/pkg/mono-addins*`
2. `sudo pacman -Syy`

Closing the issue because it's probably out of scope, if you thing it's a mistake just re-open it and provide further information.
