### ISSUE TITLE
Failed to start login Service

### ISSUE THREAD

**Issue by sayantanHack** [BlackArch/blackarch#1828]
HI there ,I faced a problem I posted before. I forgot my password . No idea helped me.
 At last I installed the Black arch again from ISO 2017. 08.30 .But after installing successfully I reboot it . Then while rebooting process is going on then suddenly I got the message "**Failed to start login service**"
, see '**systemctl status systemd-logind.service**' for details. 
Plz help me this is very bad I cannot start this. Each time there must be an issue. plz do or tell  something.

**Comment by nbulischeck** [comment]
What is the output of `systemctl status systemd-logind.service`?

**Comment by sayantandatta97** [comment]
I have completely installed it. But when I reboot system it show some errors. 
![barch](https://user-images.githubusercontent.com/26269305/33928304-99f9b7f8-e00b-11e7-8487-a4e1c5f54ad1.png)

**Comment by PedroSFreitas** [comment]
Sorry for the delay.
I think it's safe to say we have figured out the problem and it will be fixed in the near future. Probably with the next release.

Note: we'll close this issue in order to maintain a single one: https://github.com/BlackArch/blackarch/issues/1837

Now about your problem, you could just boot another live iso and change the password of the other installation. If you google it, you'll find a lot of resources on it.
