### ISSUE TITLE
nvidia drivers

### ISSUE THREAD

**Issue by mikeybro** [BlackArch/blackarch#1836]
Has any issues with nvidia drivers ever happen?
doing a pacman -S nvidia seems to cause issues with LDXE display, or the fluxbox , I am not to sure, also some other system issues happen, the system clock changes and will not stay set and also I notice some slow downs.  removing the nvidia driver has messed up the boot process and I may just reinstall or mount the drive and see if I can fix the issue from there. So the question is, does any one have any input when with the nvidia drivers?  Anything?

**Comment by mikeybro** [comment]
Any references from the arch wikis? anything??

**Comment by PedroSFreitas** [comment]
@mikeybro I left this Issue open for some time to see if other users would report anything regarding `nvidia`. But I do think it's not related to BlackArch itself, since kernel, drivers and base are from Arch Linux. It's important to remember that BA is sitting on top of Arch (repository).

I'm closing this issue, but if you think I'm wrong by closing it and you do think it's indeed related to Black Arch please *provide further information* (logs, what you did, version of the ISO you used, etc) and reopen it.

note: just fyi I have had some troubles with `nvidia` driver on an Arch Linux installation. But this is out of scope for here.
