### ISSUE TITLE
pacman keysignature fails when running the strap script

### ISSUE THREAD

**Issue by jmg87** [BlackArch/blackarch#1896]
Same as it happened with #1160 , but my keyserver was the recommended on that issue ( hkps://pool.sks-keyservers.net ). 

Changing it for the MIT key server `keyserver hkp://pgp.mit.edu:80` in /etc/pacman.d/gnupg/gpg.conf solved this.

I'm opening a new issue as I can't reopen it. I don't know if there is something to be done (looks like an issue in one of the  signing keys?) to fix this or maybe just add a note somewhere on the installation documentation?

**Comment by PedroSFreitas** [comment]
We have a FAQ entry explaining a few things that could happen during `strap.sh` process.
https://blackarch.org/faq.html

---

Adding `hkp` shouldn't be necessary on `pgp.mit.edu`. As we all have seen this issue is somehow limited to a few people only (I never got his error message for some reason), hence the FAQ entry explaining it could be a network issue rather than implementation on `strap.sh`.
However there is a PR open addressing how `strap.sh` **could avoid and treat some error messages** while receiving the key.

**Comment by PedroSFreitas** [comment]
The PR I mentioned above: https://github.com/BlackArch/blackarch-site/pull/80
