### ISSUE TITLE
Multiple package conflicts - Live ISO (2017.12.11)

### ISSUE THREAD

**Issue by user0x10** [BlackArch/blackarch#1920]
There are multiple upgrade conflicts with 'scapy4k' and 'poppler-qt' packages and 'pacman -Syu' fails to proceed. Also some of the packages are being replaced by others. Please create a new live iso with all these errors resolved.

**Comment by PedroSFreitas** [comment]
We have plans to release a new ISO in 3 weeks approximately.
Also, are you running `pacman -Syu` inside the Live Environment? If so, you're doing it wrong. Live environment aren't the place for that.

Also, the conflicts are from upstream.
Closing this since we're tracking the new ISO progress somewhere else.
