### ISSUE TITLE
Matching ISO Checksums and Signing ISOs

### ISSUE THREAD

**Issue by Soham3-1415** [BlackArch/blackarch#1933]
I cannot find the checksums for previous versions of the BlackArch isos on the BlackArch website, and it might be a good thing to sign the isos or a list of checksums like many other operating systems do.

**Comment by PedroSFreitas** [comment]
Previous versions are no longer supported, so checksums are not provided. However you can easily find them with google/github foo magic. ;)

Can you define "list of checksums"? Because the current setup seems okay for now. There is to ways to verify the checksums:

1. through our site; and
2. curl -s https://blackarch.org/checksums/{INSERT HERE FILE NAME} -> https://github.com/BlackArch/blackarch-site/tree/master/checksums

Signing them could be a thing, @noptrix what do you think?

**Comment by Soham3-1415** [comment]
I was asking about checksums for old versions because at the time of posting the new isos weren't uploaded. Only their checksums were. That is now resolved.
Some operating systems release multiple isos (like BlackArch does) and they create a single file with all the checksums. Then they sign that file. I was suggesting that as an alternative to signing each iso, as they both maintain the same level of integrity.
