### ISSUE TITLE
VMware 12 OVA hardware error

### ISSUE THREAD

**Issue by gregtampa** [BlackArch/blackarch#1937]
What was used to create the current OVA file? I am not able to import it into VMWare Workstation

**Comment by gregtampa** [comment]
The import failed because D:\VMs\ba\blackarch-linux-2018.06.01.ova did not pass OVF specification conformance or virtual hardware compliance checks.

Click Retry to relax OVF specification and virtual hardware compliance checks and try the import again, or click Cancel to cancel the import. If you retry the import, you might not be able to use the virtual machine in VMware Workstation.

**Comment by gregtampa** [comment]
Line 102: Unsupported element 'StorageItem'.

Line 111: Unsupported element 'StorageItem'.

Line 120: Unsupported element 'EthernetPortItem'.

**Comment by PedroSFreitas** [comment]
@gregtampa We'll take a look.

Did you try to import is as V1, or do what the message says "Click Retry"?

**Comment by gregtampa** [comment]
Thanks I went on IRC and asked, the reply was it's not a blackface issue so I left. 
I just installed from the iso instead.
I just clicked open in VMware there is no version selection. 
In order to solve the issue you must unzip the ova file and edit the config file or something. 
The exact error message was on my 2nd reply. Options was cancel or retry

**Comment by PedroSFreitas** [comment]
I think I remember someone asking about Network configuration in VirtualBox or something, which I replied it's not a BlackArch issue. But **I do not remember** someone asking about this particular issue that you're having.

Either way, I think the problem relies on the OVA version format. We chose V2 because it's a more recent version and on our tests we didn't see any problem with the importation process. But as I said before, we're going to check it again. **Thanks for your report.**

**Comment by benlarsendk** [comment]
Yeah, same problem here. Any "easy" solution?

**Comment by noptrix** [comment]
can you simply 'retry' (2nd try) and let us know if it still persists? i sucessfully imported it via vmware workstation player

**Comment by Tazmain** [comment]
I managed to use the new .ova in workstation 9, any higher version will work.

**Comment by Tazmain** [comment]
@gregtampa did you manage to get the new OVA imported?
