### ISSUE TITLE
[upstream] smbmap: dependency issue

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2325]
For upstream tracking.

### Bug description

```
$ smbmap
Traceback (most recent call last):
  File "/usr/bin/smbmap", line 19, in <module>
    from impacket import version, smbserver
  File "/usr/lib/python2.7/site-packages/impacket/smbserver.py", line 48, in <module>
    from impacket import smb, nmb, ntlm, uuid, LOG
  File "/usr/lib/python2.7/site-packages/impacket/smb.py", line 54, in <module>
    from impacket.krb5.gssapi import KRB5_AP_REQ
  File "/usr/lib/python2.7/site-packages/impacket/krb5/gssapi.py", line 19, in <module>
    from Cryptodome.Hash import HMAC, MD5
ImportError: No module named Cryptodome.Hash
```

### Steps to reproduce

Install it.

### Info

Waiting the upstream maintainer move from `pycrypto` to `pycryptodome`.

- Actual requirements.txt: https://github.com/ShawnDEvans/smbmap/blob/master/requirements.txt
- PKGBUILD: https://github.com/BlackArch/blackarch/blob/master/packages/smbmap/PKGBUILD
- upstream issue: [migrating from pycrypto to pycryptodome](https://github.com/ShawnDEvans/smbmap/issues/31)

**Comment by noptrix** [comment]
@noraj thanks a lot :)

**Comment by Edu4rdSHL** [comment]
Hello @noraj it isn't an issue with upstream, the issue is with the impacket package of ArchLinux 
```
File "/usr/lib/python2.7/site-packages/impacket/krb5/gssapi.py", line 19, in <module>
    from Cryptodome.Hash import HMAC, MD5
```
it package requires `python2-pycryptodomex` but isn't include as dependency in ArchLinux package. See https://bugs.archlinux.org/task/61617#comment179261

I've fixed it via https://github.com/BlackArch/blackarch/commit/9669c86c531e7fcbcbf743a562374d1aabe2738b
