### ISSUE TITLE
[Tool updates] SSLyze & SSLScan

### ISSUE THREAD

**Issue by s7x** [BlackArch/blackarch#2328]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Info for developers

Hi there! Just a little bump for those 2 fantastic tools. Here are the last versions:

**SSLyze**:  2.0.6 
**SSLScan**:  1.11.11-rbsec 

Cheers!

**Comment by noptrix** [comment]
@s7x thanks for this. sslscan is maintained by arch community. and it was flagged already since 2017. they didn't manager to update the package yet. maybe ask them. and for sslyze: python-nassl cannot be built due to an old error related to SSL. dev still didn't fix it. maybe also ask them to fix it :)

**Comment by noraj** [comment]
Also SSLscan is useless since there is testssl that is far mroe reliable and complete.
