### ISSUE TITLE
[Tool Request] VSCodium

### ISSUE THREAD

**Issue by vemi21** [BlackArch/blackarch#2338]
It could be really helpfull for programming on BlackArch.

https://vscodium.com/

**Comment by noraj** [comment]
Hi @vemi21 of course VScode is awesome but you must know that VScode has a MIT license for it source and a custom MS license for binaries but since several months the ArchLinux team moved the vscode package from AUR to official community repo: https://www.archlinux.org/packages/community/x86_64/code/

So before there were 2 AUR package one from source that has a opensource license but was long to build and another from binaries but with a MS license.

Now that The ArchLinxu team has moved in in official repo, you have the prebuilt binary version crafter by the Arch team **with** the MIT license! https://www.archlinux.org/packages/community/x86_64/code/

So VSCodium maybe useful for distro which are not in this case but is totally useless for ArchLinux. So I think we can close this.
