### ISSUE TITLE
BeRoot

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2478]
https://github.com/AlessandroZ/BeRoot

**Comment by noraj** [comment]
- [ ] setup.py https://github.com/AlessandroZ/BeRoot/issues/28

**Comment by noraj** [comment]
Like for peass or linenuim, just need to copy in /usr/share as it is meant to be copied on target machine and not used as a tool.

**Comment by pwnfoo** [comment]
For the Linux one, it looks like it has [a dependency](https://github.com/AlessandroZ/BeRoot/blob/master/Linux/beroot.py#L7) on the beroot folder present in the directory, so copying just the .py file will not work.

Does it make sense to zip/tar the entire folder and store in `/usr/share` so that it's easier to copy it to the target system?

**Comment by noraj** [comment]
> Does it make sense to zip/tar the entire folder and store in `/usr/share` so that it's easier to copy it to the target system?

Not because you can't review it, or use a find on a .py file etc. if it is archived. Also depending of what is availalbe on the target system and the level of furtive required the use won't use the same archive so better keep it unarchived.

**Comment by noraj** [comment]
Packaging work was made in https://github.com/BlackArch/blackarch/pull/3196/commits/f748d66765ee34269bb404f5f8226736265d192f as part of PR #3196 but has been stopped until a license issue is resolved https://github.com/AlessandroZ/BeRoot/issues/36

**Comment by D3vil0p3r** [comment]
Just contacted the developer for the LICENSE

**Comment by D3vil0p3r** [comment]
@noraj https://github.com/BlackArch/blackarch/pull/4224
