### ISSUE TITLE
[Tool request] Osmedeus

### ISSUE THREAD

**Issue by pranqster** [BlackArch/blackarch#2562]
Tool that allows you to automate reconnaissance and vulnerability scanning against targets.

https://github.com/j3ssie/Osmedeus

**Comment by CyberGhazi786** [comment]
Better to close the BlackArch project. You love to deny users' requests. It's very easy to say, "Use Docker Compose," but do you know that Docker Composers lack many of the functions of these frameworks? I am very upset and disappointed by your ignorant comments that you reply against all tools or framework requests on BlackArch Linux platform. I am leaving BlackArch and moving back to kali linux because these people at least satisfy their users' requests. Goodbye. Black Arch is a junk yard of obsolete tools and scripts that no one uses in current times.
BlackArch Linux R.I.P 🫡💐👋🙏♥️👍

**Comment by D3vil0p3r** [comment]
https://github.com/j3ssie/osmedeus/issues/284

**Comment by D3vil0p3r** [comment]
I would close this issue:
* It is just a bunch of tools collector (https://github.com/osmedeus/osmedeus-base/blob/main/Dependencies.md) and a lot of them are not packaged in Arch
* It needs of [osmedeus-base](https://github.com/osmedeus/osmedeus-base) repository to be in `$HOME` otherwise `osmedeus` produces an error. We can still patch [source files](https://github.com/j3ssie/osmedeus/blob/main/cmd/root.go) to change this check to another dir like `/usr/share/osmedeus-base`
* Project maintainer seems to be AFK both on Discord and GitHub

In the future we can think to deploy it as container, but currently I would close this.

**Comment by pranqster** [comment]
Fine by me to close.
