### ISSUE TITLE
[Tool Request] RustScan - Remove this useless wrapper

### ISSUE THREAD

**Issue by ikstream** [BlackArch/blackarch#2810]
https://github.com/brandonskerritt/RustScan

**Comment by Brueggus** [comment]
Shouldn't we use their release versioning?
https://github.com/RustScan/RustScan/releases

**Comment by noraj** [comment]
@Brueggus BA goal is to be the more bleeding edge possible. For now there is only one repository canal so git is preferred over release bundle. But in the future we may introduce a bleeding edge canal and a release canal, kindda like stable and testing.
Coz many sec tools don't have a clean devops process, so some have no release at all or some create a release once every 3 years when the git is updated everyday so the last release doesn't even work anymore.

**Comment by Edu4rdSHL** [comment]
We should remove this shitty wrapper from our repos to be honest.

**Comment by noraj** [comment]
I agree the author says it's tool is faster than nmap but his benchmark is wrong, he doesn't know how to properly launch a nmap scan. This wrapper is useless you can do the same with xargs in oneline but it not even useful since you can use nmap verbose output to get results in realtime instead of waiting the end of the scan and that by default nmap run scans already multi-threaded so all wrapper running several nmap intances in parallel are useless and made by guys who don't know how nmap works. It was maybe useful times ago for old versions of nmap when it wasn't multi-threaded.
Anyway a wrapper can't be faster than the tool it wraps lol
