### ISSUE TITLE
[Tool request] maigret

### ISSUE THREAD

**Issue by DeadNumbers** [BlackArch/blackarch#2848]
- **Name**: maigret
- **Source URL**: https://github.com/soxoj/maigret

**Comment by DeadNumbers** [comment]
New source link https://gitlab.com/soxoj/maigret/

**Comment by soxoj** [comment]
Actual link: https://git.rip/soxoj/maigret

**Comment by Edu4rdSHL** [comment]
Hey @soxoj thank you for the heads up. @dualfade hi, please, can you update the url and pkgver/pkgrel in the PKGBUILD?

**Comment by dualfade** [comment]
Will do.

**Comment by Edu4rdSHL** [comment]
@soxoj we discovered that maigret repo was taken down by DMCA infringement, I'm not going to merge https://github.com/BlackArch/blackarch/pull/2899 until the situation in clear, if this starts causing issues for us then the package will be dropped. @snooppr sorry for the ping, please let us know your thoughts about this package in our distro.

**Comment by snooppr** [comment]
> @soxoj we discovered that maigret repo was taken down by DMCA infringement, I'm not going to merge #2899 until the situation in clear, if this starts causing issues for us then the package will be dropped. @snooppr sorry for the ping, please let us know your thoughts about this package in our distro.

Thanks for the ping.  

Please do not merge this PR.  This is a scam on the part of Soxoj.  He hacked the full version of the commercial Snoop https://github.com/snooppr/snoop and got blocked on Github / Gitlab.  Here is evidence of his guilt from his last link
https://youtu.be/Z_titGNXm6g

**Comment by Edu4rdSHL** [comment]
Thanks for clarifying it, @snooppr. We will delete this package from our repositories.

**Comment by snooppr** [comment]
https://github.com/BlackArch/blackarch/pull/2877
thanks, remove "maigret" from the distribution completely.  Thank you for letting us know.

**Comment by soxoj** [comment]
Hey @DeadNumbers @Edu4rdSHL @dualfade. Glad to notify that the [maigret repository](https://github.com/soxoj/maigret) has been unlocked. GitHub has reviewed my [DMCA counter-notice](https://github.com/github/dmca/blob/master/2020/11/2020-11-12-Snoop-counternotice.md) and accepted it. Thus there are no problems with the DMCA now.

And, of course, my project is not a scam - maigret scan sites that snoop scan also, but "copyright on the list of sites" is nonsense.

**Comment by snooppr** [comment]
@Edu4rdSHL Hello, sorry for the ping. Write me a private message snoopproject@protonmail.com.

**Please do not include the Maigret repository in OS BlackArch.**

The Maigret repository has infringed the Snoop Project's copyright and this is not related to what it claims: "copyright on the list of sites".
He copied the BDFul Snoop Project database (these are not only links, the BDFull database contains unique detection methods, names, this is a scientific work that includes more than six months of work).
I'm trying to get his full name from Github (as per Github policy) so I can file a copyright infringement lawsuit. The copyright infringer (soxoj) is currently anonymous and his repository is scam. I hope that Github will provide me with the full details of the intruder shortly in order to move the dispute to lawsuit.

Github is not a judge and does not consider evidence with discretion (it is Github's official policy to adhere to the minimum requirements: accept documents (address, emai, signature, name).
Here is the counter-notification of the offending soxoj:
https://github.com/github/dmca/blob/master/2020/11/2020-11-12-Snoop-counternotice.md
For example, soxoj talks about a fork under the GPL license (the repositories mentioned in the case were never under the GPL license, Sherlock and Maigret are MIT, Snopp is a commercial license). And the points he lists are perjury.
This increases his responsibility before the law.

Immediately after unlocking the repository, soxoj deleted all commits in his Maigret repository and faked the repository creation date and included the BDFull database from the Snoop Project (see the first commit date, this is January 2020, but the maigret repository was created in August 2020, and the Snoop Project repository in February 2020): https://github.com/soxoj/maigret/commits/main.
For comparison, I did the same trick with my duplicate repository (and allegedly created it back in 1997, only Github did not exist then), for example: https://github.com/snooppr/Snoop_Project_Demonstration_of_creation_date/commits/master.
However, the user's history is displayed in the api (which is not fake): https://api.github.com/users/soxoj/events/public

I will add that the user soxoj for copyright infringement (after blocking on Github, soxoj moved Maigret_scam to Gitlab) in this case was blocked on Gitlab and has no right to restore his account on the Gitlab platform:
https://gitlab.com/soxoj

If you need more evidence (maigret / snoop repository inspection protocol, maigret fork (copied, real), video and data from the web archive of the Internet, write to me on ls).
Best regards, Snoop Project developer.

**Comment by Edu4rdSHL** [comment]
Hello, @snooppr and @soxoj, I hope you're having a good day. To be honest, I'm tired of this discussion, it's getting exhausting and I'm not going to be in the middle of it, if you want to solve your differences you can do it through private messages and then you can come back when you have done it, discussions are not the main purpose of a PR. If you want to notice something different then send me a email to edu4rdshl[at]protonmail.com, thanks. I'm not going to add `maigret` until you solve your differences.

Regards,
Edu4rdSHL
