### ISSUE TITLE
tool request: anonsurf

### ISSUE THREAD

**Issue by Cloufish** [BlackArch/blackarch#2922]
- **Name**: anonsurf
- **Source URL**: https://github.com/ParrotSec/anonsurf
OR
https://github.com/Und3rf10w/kali-anonsurf

**Comment by Edu4rdSHL** [comment]
These tools are made for deb-only distros. Also, we already have packages who does the same task such as `tor-router`

**Comment by CyberGhazi786** [comment]
$ sudo pacman -S tor-router
error: could not register 'multilib' database (database already registered)
error: could not register 'multilib' database (database already registered)
error: could not register 'multilib' database (database already registered)
error: could not register 'multilib' database (database already registered)
resolving dependencies...
looking for conflicting packages...

Package (1)           New Version  Net Change  Download Size

blackarch/tor-router  4.001a510-1    0.08 MiB       0.02 MiB

Total Download Size:   0.02 MiB
Total Installed Size:  0.08 MiB

:: Proceed with installation? [Y/n] Y
:: Retrieving packages...
 tor-router-4.001a510-1-any       15.9 KiB  23.1 KiB/s 00:01 [--------------------------------] 100%
(1/1) checking keys in keyring                               [--------------------------------] 100%
(1/1) checking package integrity                             [--------------------------------] 100%
(1/1) loading package files                                  [--------------------------------] 100%
(1/1) checking for file conflicts                            [--------------------------------] 100%
:: Processing package changes...
(1/1) installing tor-router                                  [--------------------------------] 100%
BlackArch ==> Making a backup of your torrc file, if you have problems with the new configuration, delete /etc/tor/torrc and move /etc/tor/torrc.backup to /etc/tor/torrc
BlackArch ==> Configuring the torrc file to use TOR as a transparent proxy...
:: Running post-transaction hooks...
(1/2) Reloading system manager configuration...
(2/2) Arming ConditionNeedsUpdate...
[cyberghazi786@cyberghazi786-vmwarevirtualplatform ~]$ tor-router
The tor service is not active, please start the tor service before running the script.
[cyberghazi786@cyberghazi786-vmwarevirtualplatform ~]$ systemctl start service tor
Failed to start service.service: Unit service.service not found.
Job for tor.service failed because the control process exited with error code.
See "systemctl status tor.service" and "journalctl -xeu tor.service" for details.
