### ISSUE TITLE
Update: pfff

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#2986]
pfff from facebook is archived: https://github.com/facebook/pfff -> https://github.com/facebookarchive/pfff
pfff is now here: https://github.com/returntocorp/pfff

Please update: https://github.com/BlackArch/blackarch/tree/master/packages/pfff

Many thanks guys for your great efforts!

**Comment by pwnfoo** [comment]
More info: 
A lot of changes have gone into the new pfff since the new release, so will have to validate if the patches are still relevant.

`external/ocamlzip` folder no longer exists too, so the current PKGBUILD will have to be rewritten.

**Comment by D3vil0p3r** [comment]
It has been migrated here: https://github.com/returntocorp/semgrep/blob/develop/semgrep-core/src/pfff/README.md but it is not clear how to retrieve the source files. There is an install section in this wiki http://github.com/returntocorp/pfff/wiki/Main but it seems outdated because the pfff repo reported there has not the source files anymore.

**Comment by D3vil0p3r** [comment]
Here an update: https://github.com/returntocorp/semgrep/issues/6781#issuecomment-1374002162

@noraj At this point `pfff` should be removed?

**Comment by noraj** [comment]
> Here an update: [returntocorp/semgrep#6781 (comment)](https://github.com/returntocorp/semgrep/issues/6781#issuecomment-1374002162)
> 
> @noraj At this point `pfff` should be removed?

Yes. At the light of https://github.com/returntocorp/semgrep/issues/6781, I think pfff (at least for now) is just a core component of semgrep and has no purpose alone. So now that the pfff repo was removed we can't add it to the deprecated list and remove the `pfff` package dependency of `pfff` since `pfff` is now included in semgrep itself.
