### ISSUE TITLE
klar

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#2989]
- **Name**: klar
- **Source URL**: https://github.com/optiopay/klar

**Comment by dualfade** [comment]
Holding. 

Build fail due to outdated libs.

==> Starting pkgver()...                                                                                                                       
==> Starting build()...                                                                                                                        
package github.com/optiopay/klar: cannot find package "github.com/coreos/clair/database" in any of:                                            
        /usr/lib/go/src/github.com/coreos/clair/database (from $GOROOT)                                                                        
        /build/klar/src/src/github.com/coreos/clair/database (from $GOPATH)                                                                    
==> ERROR: A failure occurred in build(). 

Notes:
vendor/github.com/coreos/clair/api/v3/clairpb/convert.go
21:     "github.com/coreos/clair/database"

Why ?
No longer exists --
New Lib Url Path --
--> github.com/quay/clair

Issue has existed with src build since 
May 3rd 2020 --
https://github.com/optiopay/klar/issues

**Comment by Edu4rdSHL** [comment]
I think that you can `sed` the file and replace the URL, that should work unless the library isn't backward compatible.

**Comment by dualfade** [comment]
I suggested that to Noptrix as well. I do not know if it's backwards compatible, however I am happy to try if this application is warranted by the team.

D

**Comment by Edu4rdSHL** [comment]
This package is broken in many ways, bassically everything that depends in github.com/coreos/* is giving a 404. At the moment this will be packaged using the binary provided in https://github.com/optiopay/klar/releases/tag/v2.4.0

**Comment by Edu4rdSHL** [comment]
This has been packaged, I hope that upstream fix the build. If that happens, please let me know and then we will compile from source.

Ref: https://github.com/optiopay/klar/issues/174
