### ISSUE TITLE
raccoon conflict

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#2992]
raccoon (https://github.com/evyatarmeged/Raccoon) is conflicting with https://aur.archlinux.org/packages/raccoon/

**Comment by noraj** [comment]
You mean that raccoon package in BA (based on https://github.com/evyatarmeged/Raccoon) has a namespace conflict with raccoon from the AUR (based on https://github.com/onyxbits/Raccoon/) which are not the same tools but have the same name.

A rude (but true) answer would be to say the BA repo is only trying to keep compatibility with ArchLinux repo and not other unofficial third party repos (AUR, Manjaro, xyne, or [hundred of others](https://wiki.archlinux.org/index.php/unofficial_user_repositories)).

A thing that is technically possible is to rename the BA package into racoon-recon or something but this can also be that @vdun you ask the same at https://aur.archlinux.org/packages/raccoon/ to change the other racoon into racoon-apk or something because as I said we can't possibly keep compatibility with all unofficial third party repos.

@Edu4rdSHL @noptrix What do you think? I personally think we should not change our package name.

**Comment by Edu4rdSHL** [comment]
Hello, @vdun, @noraj. We are not going to change package names for every package that conflicts with different repos that official ArchLinux ones, if that package is moved to the official AL repos at some point while keeping the same name, then we may change our package name.

Regards,
Ed

**Comment by noraj** [comment]
@vdun So yeah @Edu4rdSHL thinks the same as me, you better go the other way around by notifying the AUR package maintainer.
