### ISSUE TITLE
quark-engine: missing freshquark

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#2993]

**Comment by 18z** [comment]
hi @vdun 

This is because blackarch is using the old version of quark.

**Comment by pwnfoo** [comment]
Thanks a lot for the constant support @vdun!

**Comment by krnick** [comment]
Hello @pwnfoo @vdun ,

Thank you for integrating quark-engine into BlackArch. I (co-founder) and @18z (Founder) are very happy to contribute to BlackArch. We would like to know if there is any mechanism that will allow us to update to BlackArch when we update the quark version at the same time.

For example, Github's Action Hook

Thank you so much!

**Comment by pwnfoo** [comment]
@krnick, instead of pulling from a release, we can change the source to your master branch, provided your master is always stable. That way, it'll always be bleeding edge.

**Comment by krnick** [comment]
@pwnfoo cool, thank you 😄 , please let me know if there is anything I can help.

**Comment by 18z** [comment]
@pwnfoo 

I don't get the idea of ```change the source to your master branch```.
Can you give us some hint? :D

**Comment by pwnfoo** [comment]
@18z Sure, we currently [pull from your release section](https://github.com/blackarch/blackarch/blob/c761b3870c8aa872547ec15b1a82016966ea1ca8/packages/quark-engine/PKGBUILD#L16)  and this is manually bumped (the team is currently working on automation around this).

Instead of this, we can change the source to the master branch (see source line in [amass PKGBUILD](https://github.com/BlackArch/blackarch/blob/ece47e040169f35933bf26f306af409d15a4db3a/packages/amass/PKGBUILD#L15) for reference). This will ensure that the packages are [bumped up more often](https://github.com/BlackArch/blackarch/commit/dc16cc1153613e9e5dc81698aa578a7aacf4a5cf).

Hope that answers your question.
