### ISSUE TITLE
Install without overwriting existing triple boot partitions

### ISSUE THREAD

**Issue by v3n0m0x** [BlackArch/blackarch#3040]
I'm stuck trying to switch to  Blackarck and install on a  GPT disk which already has parrot os, red hat and windows. Grub2 is on the first partition.  After i select free space On sda and answering no to zeroing out ,the installer says it will write boot on sda1 root to sda2  and so on..The problem is those partitions are already occupied
and i don't want to overwrite them. How can i overcome that? Do i have to manually create and format the partitions first? I'm afraid my existing partitions will get overwriten if i proceed with installer..I would really appreciate some help thank's

**Comment by noraj** [comment]
Hi @v3n0m0x, I'm sorry to hear you have problems installing BA.

I'm closing the issue because there is nothing related to BA here, you are asking for support for multi-boot installation.

The [Dual Boot](https://wiki.archlinux.org/index.php/Dual_boot_with_Windows)  AL Wiki page may help you. Else [contact us](https://github.com/BlackArch/blackarch/issues/new/choose) on discord or IRC.

**Comment by v3n0m0x** [comment]
Ok sorry for being off topic i did't know where to ask. I'm on my way :-D
