### ISSUE TITLE
usbutils dependency missing in aircrack-ng package

### ISSUE THREAD

**Issue by ViniciusMesquita-O** [BlackArch/blackarch#3041]
When I try to run the airmon-ng to enter on monitor mode, the same informs that the lsusb from usbutils is not present.
I'm using the full iso live.

**Comment by aancw** [comment]
Pacman -S usbutils
https://archlinux.org/packages/core/x86_64/usbutils/

**Comment by Edu4rdSHL** [comment]
@ViniciusMesquita-O thank you for the report, it's a valid bug with the `aircrack-ng` package provided by ArchLinux which doesn't include `usbutils` as dependency. Please report this bug to [ArchLinux package](https://archlinux.org/packages/community/x86_64/aircrack-ng/) using the "Add new bug" option.

This bug is also affecting us, if AL doesn't take a quick action on this then I will fix it directly here (I don't want to interfere with AL packages as much as possible).

I will keep this open for tracking.

**Comment by aancw** [comment]
@Edu4rdSHL It's already opened as bug in tracker but no response

https://bugs.archlinux.org/task/66140?project=5&string=aircrack-ng

**Comment by Edu4rdSHL** [comment]
This have been fixed in https://github.com/archlinux/svntogit-community/commit/1143534e99efa084a9c42811f619d0955521884e
