### ISSUE TITLE
Install Black arch on MacBook M1 pro 

### ISSUE THREAD

**Issue by mr-tanta** [BlackArch/blackarch#3393]
Type: Question

## Question
Is it posible to install black arch on MacBook M1 pro 2021?

**Comment by anunna** [comment]
No, it is not supported by Arch Linux ([notice](https://wiki.archlinux.org/title/mac)), therefore it is not supported by BlackArch in any official way.

However there is a downstream arch based [project](https://asahilinux.org) for M1 Mac. I do to know how well this works and can't officially speak for them. Should this work and since M1 chips are ARM based, BlackArch does have support for ARM based packages, it should work if you get the above unofficial distribution running; do keep in mind that any x86_64 packages will not work. 

No testing of this is done by BlackArch obviously and whatever issues you run into specific to Apple or AsahiLinux, we do not support.

You will have to test all this and see how it works for you.
