### ISSUE TITLE
[metasploit] msfconsole session background issue with custom AL wrapper

### ISSUE THREAD

**Issue by gillouche** [BlackArch/blackarch#3438]
Type: Question

## Question
Hello,

currently, I have BlackArch installed in a VM, I am using Arch as the host.

When I have a reverse shell via Metasploit and press CTRL+Z, the msfconsole gets sent in the background, not the Metasploit session.

Any idea how I should configure my VirtualBox/Guest OS/Host OS to be able to background the session in Metasploit using CTRL+Z (or any other shortcut, I don't mind).

I found this [issue](https://github.com/rapid7/metasploit-framework/issues/8860) in Metasploit framework which triggered the creation of this [issue](https://bugs.kali.org/view.php?id=7646) in Kali so maybe there is something that needs to be done on BlackArch to have it working as well?

Thanks.

**Comment by gillouche** [comment]
I manually added `trap "" TSTP` in /usr/bin/msfconsole as a temporary fix but that will be removed at the next update.

```bash
#!/bin/sh

trap "" TSTP
BUNDLE_GEMFILE=/opt/metasploit/Gemfile bundle-2.7 exec ruby-2.7 /opt/metasploit/msfconsole "$@"
```

**Comment by noraj** [comment]
Metasploit package is not maintained by BA but by AL team.

- https://archlinux.org/packages/community/x86_64/metasploit/
- https://github.com/archlinux/svntogit-community/blob/packages/metasploit/trunk/PKGBUILD

It seems the issue was resolved upstream by adding `exec` (cf for the omnibus install https://github.com/rapid7/metasploit-omnibus/pull/160/files, or for kali msfdb wrapper https://gitlab.com/kalilinux/packages/metasploit-framework/-/commit/44832aff2ee52eebc73c6ea08bed7863fd9415cf)

So the wrapper `/usr/bin/msfconsole` must be change like this (and maybe msfdb or all binaries calling msfconsole):

```diff
-BUNDLE_GEMFILE=/opt/metasploit/Gemfile bundle-2.7 exec ruby-2.7 /opt/metasploit/msfconsole "$@"
+BUNDLE_GEMFILE=/opt/metasploit/Gemfile exec bundle-2.7 exec ruby-2.7 /opt/metasploit/msfconsole "$@"
```

But since it's in a loop https://github.com/archlinux/svntogit-community/blob/9026ed44095904115595c5f483e5d4a23dba6ca8/trunk/PKGBUILD#L50-L54 it will require an exception for this wrapper.

So the best would be you @gillouche open an issue at https://bugs.archlinux.org/?project=5&string=metasploit

**Comment by gillouche** [comment]
Thanks @noraj, I'll open an issue on ArchLinux bug trackers.

**Comment by anthraxx** [comment]
@noraj as far as I see, the exec can be done for all binaries inside the loop. I don't think this requires an exception.

**Comment by sempervictus** [comment]
As i mentioned in the upstream issue, i am an Arch user (with the added fun of mprotect management making RVM a joy), and you'll find me in the MSF commit logs back to the days of SVN.
The way i manage this mess, and have ever since the nightmares ~10y ago around readline/rb-readline/MRI-flux, is:
```
trap "" 20
export RAILS_ENV=production
export RUBYOPT="-W0"
export JAVA_HOME="/usr/lib/jvm/default"
rvmsudo /opt/metasploit4/msf4/msfconsole -qx -r /<path-to-your>/msfconsole.rc -L
```
which uses the native Readline library and handles trapping `SIGTSTP` which is quite handy when you need to pass it into a `cmd` shell channelized inside of a session...

For packaging purposes, suggest compiling RVM's Ruby with the `railsexpress` patchset - there's a fair amount of Rails in here, along with a ton of rather complex infrastructure code in Rex all of which benefit a fair deal.

As a side-note, we use Ruby 3 nowadays.

**Comment by anthraxx** [comment]
Please test metasploit `6.2.0-2` from `[community-testing]`, it uses ruby 3.0.4 now. After some positive feedback i'll move it to the stable repo.

**Comment by gillouche** [comment]
Yes, it works @anthraxx, thanks.
