### ISSUE TITLE
Bad return status for module build on kernel: 5.18.11-arch1-1 (x86_64)

### ISSUE THREAD

**Issue by clides** [BlackArch/blackarch#3465]
Type: Question

## Question

I ran the command to update blackarch:

`sudo pacman -Syu`

and I got this issue where it says:

```
==> dkms install --no-depmod chipsec/1525.687a2ec7 -k 5.18.11-arch1-1
/sbin/dkms: line 1033: sha512: command not found
==> dkms install --no-depmod tyton/80.56494f3 -k 5.18.11-arch1-1
Error! Bad return status for module build on kernel: 5.18.11-arch1-1 (x86_64)
Consult /var/lib/dkms/tyton/80.56494f3/build/make.log for more information.
==> WARNING: dkms install --no-depmod tyton/80.56494f3 -k 5.18.11-arch1-1' exited 10
==> dkms install --no-depmod pfring/3342.cabd2381 -k 5.18.11-arch1-1
Error! Bad return status for module build on kernel: 5.18.11-arch1-1 (x86_64)
Consult /var/lib/dkms/pfring/3342.cabd2381/build/make.log for more information.
==> WARNING: `dkms install --no-depmod pfring/3342.cabd2381 -k 5.18.11-arch1-1' exited 10
==> depmod 5.18.11-arch1-1
```

and when I restart the VM, it cannot boot up.

Do anyone know how to fix the issue? Any help would be greatly appreciated

**Comment by noraj** [comment]
What are the kernel modules or drivers you installed from BA repository?

**Comment by clides** [comment]
I just installed the blackarch slim and did "sudo pacman -Syu --needed --overwrite='*' blackarch" at first. After I did "sudo pacman -Syu" weekly and this issue occurred, I don't think I downloaded any modules or drivers specifically/

**Comment by noraj** [comment]
Hum you ran `sudo pacman -Syyu --needed blackarch --overwrite='*'` written on the [download page](https://blackarch.org/downloads.html). Which has a similar effect as `sudo pacman -S blackarch`, installing all of the [2812](https://blackarch.org/tools.html) tools. Which should never be done, that's why we removed it from the website https://github.com/BlackArch/blackarch-site/pull/152. There are a few abandoned or broken tools so installing all tools will include those and have a change to break your system.

As described the goal of the Slim ISO is to provide [a selected set of common/well-known tools and system utilities](https://github.com/BlackArch/blackarch-iso/blob/master/slim-iso/packages.x86_64), so you can install a few manually on top of that. If you want a functional BlackArch Linux system with [all the available tools in the repo at build time](https://github.com/BlackArch/blackarch-iso/blob/master/full-iso/packages.x86_64), install the full ISO. But doing `sudo pacman -S blackarch` or any variant will always end bad in the end. I'll modify the documentation.

I guess the example you followed (see below) is meant to overcome some common problems when installing some packages.

```bash
# Note - it maybe be necessary to overwrite certain packages when installing blackarch tools. If
# you experience "failed to commit transaction" errors, use the --needed and --overwrite switches
# For example:
$ sudo pacman -Syyu --needed blackarch --overwrite='*'
```

But I'll replace `blackarch` (the meta group including all tool) with a package placeholder, else people may accidentally try to install all the repository like you did. I guess the example was meant so people encountering an error would replace `blackarch` with the package they were trying to install initially.

**Comment by clides** [comment]
Oh ok thanks, is there any ways to fix this vm or do I have to make a brand new slim?

**Comment by noraj** [comment]
I fear it will be 20 times more work to try to fix it rather than reinstall.
