### ISSUE TITLE
 Update problem due to invalid signature  Levon 'noptrix' Kayan

### ISSUE THREAD

**Issue by Slider0008** [BlackArch/blackarch#3505]
**Hi all. I have a problem. Can't update system.**
**The system was installed from BlackArch Linux 64 bit Full ISO.**

```
GPGME error: No data.
error: failed to synchronize all databases (invalid or corrupted database(PGP signature))
```

**Performed:**

1)   

`sudo rm -rf /etc/pacman.d/gnupg/ && sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman -Syy`

**Single key error.**

```
error: blackarch: unknown key "F9A6E68A711354D84A9B91637533BAFE69A25079"
:: Import PGP key F9A6E68A711354D84A9B91637533BAFE69A25079? [Y/n] y
error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is unknown trust
```

2)

`sudo rm -rf /etc/pacman.d/gnupg/ && sudo pacman-key --init && sudo pacman-key --populate archlinux blackarch && sudo pacman-key --update --keyserver keyserver.ubuntu.com`

**Repo Black. Executed without errors.**

3)

`sudo pacman-key --recv-keys keyid && sudo pacman-key --lsign-key keyid && sudo pacman -Syu`
**I don't understand what is **_keyid_** in this command.... Arch Wiki  -> pacman-key** [https://wiki.archlinux.org/title/Pacman/Package_signing](url)
 
**Signing this key locally failed.**

**Please help me! How to solve a problem?**

**Comment by noraj** [comment]
2. Was the right option (the one mention in [FAQ](https://blackarch.org/faq.html))

![image](https://user-images.githubusercontent.com/16578570/188514566-9ecd4952-18b7-4261-b153-5da48d025c77.png)

keyid is the key id, the one missing but you don't need 3. if you executed 2.

**Comment by Slider0008** [comment]
I did step 2, but when I update, this error pops up again.

**Comment by noraj** [comment]
You can re-try step by replacing keyid by `F9A6E68A711354D84A9B91637533BAFE69A25079`

**Comment by Slider0008** [comment]
You mean like this:  sudo pacman-key --recv-keys "F9A6E68A711354D84A9B91637533BAFE69A25079" && sudo pacman-key --lsign-key "F9A6E68A711354D84A9B91637533BAFE69A25079"     ???

**Comment by noraj** [comment]
you can use either the full id or the short version

**Comment by Slider0008** [comment]
sudo pacman-key --recv-keys 7533BAFE69A25079 && sudo pacman-key --lsign-key 7533BAFE69A25079 - tried. the error doesn't go away.

**Comment by Slider0008** [comment]
**Problem solved. The root of the problem was not only in the key, but also in the standard repositories. The problem in the key went away by itself.**   ¯\(°_o)/¯

**Comment by shi88ihs** [comment]
None of these CMDs worked or solved the problem for me. But..

What **_DID SOLVE_** it was: 

`sudo echo **F9A6E68A711354D84A9B91637533BAFE69A25079:4:** >> /usr/share/**pacman/keyrings**/blackarch-trusted 
sudo pacman-key --populate archlinux blackarch

##or

sudo echo **F9A6E68A711354D84A9B91637533BAFE69A25079:4:** >> /usr/share/**pacman/keyrings**/blackarch-trusted 
&& pacman-key --populate archlinux blackarch
`
Notice the redirect, ie **>** on the first CMD **to** the file: **"/usr/share/pacman/keyrings/blackarch-trusted"** a diff CMD I found had **"keyring"** instead of **"keyrings"** and it kept failing when I tried it. I Found the DIR didn't exist, but the **keyrings DIR** did exist. So I modified the CMD by one letter and everything is working. Must of been a typo ffrom the other guy that posted the cmd or it's that way on some Arch Based Systems.

I would use this CMD with a combo of the excellent ones above.
