### ISSUE TITLE
Error while installing dftimewolf

### ISSUE THREAD

**Issue by Szewcson** [BlackArch/blackarch#3521]
### Bug description

While installing dftimewolf error appears.

### Steps to reproduce

1.) Install dftimewolf
**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
error:
```
Collecting typing-extensions>=4.0.1
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    typing-extensions>=4.0.1 from https://files.pythonhosted.org/packages/ed/d6/2afc375a8d55b8be879d6b4986d4f69f01115e795e36827fd3a40166028b/typing_extensions-4.3.0-py3-none-any.whl (from azure-core==1.24.2->-r requirements.txt (line 95))
:: Running post-transaction hooks...
```

**Comment by noraj** [comment]
there were similar issues upstream https://github.com/log2timeline/dftimewolf/issues/649 and here is the upstream issue https://github.com/log2timeline/dftimewolf/issues/660

**Comment by tomchop** [comment]
FTR, we've moved away from pip and pipenv in favor of poetry to install dftimewolf. `requirements.txt` is no longer supported: https://github.com/log2timeline/dftimewolf/pull/675 (we'll be pushing pypi packages soon, althought given the plug-in nature of the code it might not be that useful)

**Comment by noraj** [comment]
> FTR, we've moved away from pip and pipenv in favor of poetry to install dftimewolf.

Nice. Here is how it is packaged currently on our repos https://github.com/BlackArch/blackarch/tree/master/packages/dftimewolf. Has it has many uncommon python dependencies we used a virtual environment template else it would be impossible to maintain for us.

> (we'll be pushing pypi packages soon, althought given the plug-in nature of the code it might not be that useful)

Currently we automatically detect changes from git directly but if you offer pypi release we could auto-update at each release easily rather than at each commit.

```bash
source=("https://files.pythonhosted.org/packages/source/${pkgname::1}/$pkgname/$pkgname-$pkgver.tar.gz")
```
