### ISSUE TITLE
Building Python BA packages by PEP517 or SetupTools PKGBUILD template?

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch#3889]
## Question

If there is a Python tool having only `setup.py` and not `pyproject.toml` file, is it more suitable to use PEP517 or SetupTools PKGBUILD template?

If we have both of `setup.py` and not `pyproject.toml`, which template we should use? And why?

**Comment by noraj** [comment]
- if pyproject.toml, use [PKGBUILD-python-PEP517](https://github.com/BlackArch/blackarch-pkgbuilds/blob/master/PKGBUILD-python-PEP517) for tool or [PKGBUILD-python-lib-PEP517](https://github.com/BlackArch/blackarch-pkgbuilds/blob/master/PKGBUILD-python-lib-PEP517) for dependency libs, because setuptools is deprecated
- if no pyproject.toml is available but setup.py use [PKGBUILD-python-setuptools](https://github.com/BlackArch/blackarch-pkgbuilds/blob/master/PKGBUILD-python-setuptools) or [PKGBUILD-python-lib-setuptools](https://github.com/BlackArch/blackarch-pkgbuilds/blob/master/PKGBUILD-python-lib-setuptools)
- if there is no pyproject.toml nor setup.py and it's a one-file python script use [PKGBUILD-generic-jointscript](https://github.com/BlackArch/blackarch-pkgbuilds/blob/master/PKGBUILD-generic-jointscript)
- for complex cases other stuff may be done, eg. [PKGBUILD-python-standalone](https://github.com/BlackArch/blackarch-pkgbuilds/blob/master/PKGBUILD-python-standalone) when it's a dependency hell
