### ISSUE TITLE
[Tool Request] - whoxyrm

### ISSUE THREAD

**Issue by EsamLasheen** [BlackArch/blackarch#4031]
- **Name**: whoxyrm
- **Source URL**: https://github.com/MilindPurswani/whoxyrm
- **Description**: A reverse whois tool based on Whoxy API.

**Comment by MilindPurswani** [comment]
Hey @anunna , 

I am the creator of this tool. Is there anything I can do to help this get pushed ahead? 

Thanks, 
Milind Purswani

**Comment by anunna** [comment]
Hi @MilindPurswani,

I was a way for most of the year. I am submitting these sometime today.

**Comment by MilindPurswani** [comment]
Hi @anunna, 

Thanks! Looking forward to the merge. Really curious, do you have metrics to understand how many folks are consuming a certain tool that you can let your authors have visibility onto? If there are any bugs, is there any mechanism to raise an issue directly through black arch?

Do you have any numbers around number of BlackArch users to-date? 

Thanks!

**Comment by anunna** [comment]
We don't have metrics for this. It would be complex since majority of our mirrors are community donated and maintained. We also do not have any usage tracking on the distro and we use the official Arch Linux package manager which does not track usage either and we have no control over it anyway. We will only know how popular a tool is based on what is said or how it is advertised publicly.  I am not aware of any Linux project that has metrics like this. 

Yes, Issues for tools offered by BlackArch can be reported here on the relevant repo, If any upstream bug is reported, we will redirect to the tool developer if not done already, some cases we provide patches, etc. 

Feel free to open a Discussion if you would like to discuss anything more and leave this topic to the tool request.
