### ISSUE TITLE
CyberKits

### ISSUE THREAD

**Issue by Lynx22237** [BlackArch/blackarch#4180]
- **Name**: CyberKITS
- **Source URL**: https://github.com/Len-L/CyberKits
- **Description**: Cyber ​​Equipment for Conducting Penetration testing and Defense server

Python

**Comment by Lynx22237** [comment]
hello, is there any progress on adding cyberkits tools?

**Comment by anunna** [comment]
Would've been great if the tool was actually in English

**Comment by Lynx22237** [comment]
sorry, it's not mine, so I can't change the language to English :(

**Comment by D3vil0p3r** [comment]
I would not package it. It leverages on several stuff related to Debian systems like `service` instead of `systemctl`, and the code is poorly developed and not flexible.

The two set of tools (Defense and Pentest) are not well structured for Python packages: one has a `setup.py` that forces a prompt during the building, and the other one has no `setup.py` and `pyproject.toml` but has a `requirements.txt`.

Finally, it is just a tool that runs other tools like nmap, clamav, fail2ban and so on... I don't see any concrete utility on it.

If you want it I can try to package, if not, please close it.

**Comment by Lynx22237** [comment]
Can you try wrapping it?

**Comment by D3vil0p3r** [comment]
It is what I did but it will be a castrated tool on an Arch environment unless the developer refactors it much better... or it deploys as container

**Comment by noraj** [comment]
https://github.com/BlackArch/blackarch/issues/2842
