### ISSUE TITLE
help, how can create boot from usb and install on H.D. without delete my data

### ISSUE THREAD

**Issue by AHMED002177** [BlackArch/blackarch#838]
how can create boot from USB and install on H.D. without delete my data
my laptop HP ProBook 4540S
I5 
6g Ram

**Comment by edunham** [comment]
@AHMED002177 If there's enough space on your hard drive, you can create a second partition and then install a Linux distribution to that partition. You'll use a bootloader, such as Grub, to select which partition you want to boot from. 

Make a complete backup of your data before trying this. 

Use the tools built into Windows to shrink the partition to which Windows is installed, and create a new one. Instructions are at http://windows.microsoft.com/en-us/windows/create-format-hard-disk-partition . Make sure the partitions are different sizes, and note the size of the one that's empty. This is because different operating systems will show partition labels differently, but a given partition's size will be the same no matter how you're viewing it. Then go through the Arch installation process and select the empty partition as the place you're installing to.

**Comment by noptrix** [comment]
download the new isos and use the new version of the installer.
