### ISSUE TITLE
chroot-install fails to install grub, regardless of installation medium

### ISSUE THREAD

**Issue by arcadiandecay** [BlackArch/blackarch#863]
I've been trying to sort this out for a few days, and refuse to give up. ;) I've been through the installation process backwards and forwards, and hit the same wall each time. I receive an error with /bin/chroot-install stating that /bin/grub-install doesn't exist.  When I ran /bin/chroot-install from /mnt/blackarch/bin/ however, it APPEARED to install properly. But,.upon reboot, I was kicked into a grub rescue console (YAY! :D ... :| ).  Any help would be greatly appreciated!  Thank you!

**Comment by noptrix** [comment]
hi. thanks for reporting this. actually, we starte dto work on the new ISOs including new version of installer. i know this bug already. it will be fixed soon. on the other side, you don't have to rely on ISO+installer in order to install blackarch linux. see: http://blackarch.org/downloads.html#install-repo also, if you are inetrested in getting the same menus and configs, youc an isntall afterwards: pacman -S blackarch-config-<windowmanager> f.e. fluxbox and pacman -S blackarch-config-lxdm (for the display login manager we use) and follow the instructions there. cheers

**Comment by arcadiandecay** [comment]
Okay, Thanks!! I did try the net install, and I forthwith same error. Is there any way I can get grub installed so that I came boot into the installation that's there, and fix everything manually?  I will probably download the newest ISO anyway, but I would love to conquer this. ;)

**Comment by nrzizrn** [comment]
Fixed in this dev tag -> https://github.com/BlackArch/blackarch-install-scripts/releases/tag/v0.8-dev
