### ISSUE TITLE
Network is dead.

### ISSUE THREAD

**Issue by Xeyter** [BlackArch/blackarch#944]
Why on blackarch network is misconfigured by default after turn on os machine?

**Comment by PedroSFreitas** [comment]
It isn't misconfigured. 
I think it's a feature... I mean, for me. 
I can "macchanger" all my network devices and then "up" them. 
But, furthermore I believe it's the Arch Linux default setting.

**Comment by PedroSFreitas** [comment]
And ...https://wiki.archlinux.org/index.php/Beginners%27_guide#Establish_an_internet_connection

;)

**Comment by Xeyter** [comment]
Thanks for replay. Yes but Thanks for reply. I already did that, before this post, but I wrote this because will be nice if everything will be changed for simple working state, like when i turned on system, network will be up automatically started, without any hesitation.

**Comment by noptrix** [comment]
hey. thx for reporting. we have to say that this is done on purpose, though. we want to let the user turn on network tools rather than leaking network/system information directly when you systems gets booted. for example, through dhcp requests, etc... you can simply fire up dhcp as 'systemctl start dhcpcd' and to enable on boottime 'systemctl enable dhcpcd' closing the issue.

**Comment by Xeyter** [comment]
Thanks bro :+1:

**Comment by ms1970** [comment]
Very Thanks.
systemctl start dhcpcd      and it go. 
BlackArch Linux 64 bit OVA Image  2017.06.18 in VirtualBox  on Windows 10
(NAT)
