### ISSUE TITLE
Nokogiri 1.6.6.3 and 1.6.6.2, and 1.6.6.4 major Issues

### ISSUE THREAD

**Issue by 404error-00101** [BlackArch/blackarch#977]
Just wondering if anybody has fixed install yet?  downloads base packs and installs...  then downloads blackarch packages and fails.  Window managers and everything else installs.  So I proceed to chroot and update my locale time and all of that good stuff for post gresql services,  I reboot into the system and proceed to download the blackarch tools...  because they failed remember?  nevertheless the packages don't have to re download rather only install having being downloaded during initial install.   Every time  it gets to arachni or metasploit the nokogiri gem always fails....  the only nokogiri gem that installs flawlessly is 1.5.5.  Not sure if anybody has figured it out yet but I would appreciate if somebody could help me thanks.

**Comment by gre5** [comment]
having the same problem here.

**Comment by danillofa** [comment]
I am also with this problem:
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby -r ./siteconf20151211-37908-18n260.rb extconf.rb --use-system-libraries
checking if the C compiler accepts ... yes
Building nokogiri using system libraries.
libxml2 version 2.6.21 or later is required!
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)
        --help
        --clean
        --use-system-libraries
        --with-zlib-dir
        --without-zlib-dir
        --with-zlib-include
        --without-zlib-include=${zlib-dir}/include
        --with-zlib-lib
        --without-zlib-lib=${zlib-dir}/lib
        --with-xml2-dir
        --without-xml2-dir
--with-xml2-include
        --without-xml2-include=${xml2-dir}/include
        --with-xml2-lib
        --without-xml2-lib=${xml2-dir}/lib
        --with-libxml-2.0-config
        --without-libxml-2.0-config
        --with-pkg-config
        --without-pkg-config
        --with-xslt-dir
        --without-xslt-dir
        --with-xslt-include
        --without-xslt-include=${xslt-dir}/include
        --with-xslt-lib
        --without-xslt-lib=${xslt-dir}/lib
        --with-libxslt-config
        --without-libxslt-config
        --with-pkg-config
        --without-pkg-config
        --with-exslt-dir
        --without-exslt-dir
        --with-exslt-include
        --without-exslt-include=${exslt-dir}/include
        --with-exslt-lib
        --without-exslt-lib=${exslt-dir}/lib
        --with-libexslt-config
        --without-libexslt-config
        --with-pkg-config
        --without-pkg-config

extconf failed, exit code 1

Gem files will remain installed in /usr/share/metasploit/vendor/bundle/ruby/2.2.0/gems/nokogiri-1.6.6.2 for inspection.
Results logged to /usr/share/metasploit/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0/nokogiri-1.6.6.2/gem_make.out
An error occurred while installing nokogiri (1.6.6.2), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.6.6.2'` succeeds before bundling.

**Comment by 404error-00101** [comment]
this has been an issue since the release of the august iso.  I don't think they plan on fixing it
